/**
 * Chat store using Zustand
 */
import { create } from 'zustand';
import { immer } from 'zustand/middleware/immer';
import type { ChatMessage, ChatResponse, StatusUpdate } from '@/types';
import { generateSuggestedPrompts } from '@/utils/promptGenerator';

interface ChatState {
  // Conversation
  conversationId: string | null;
  messages: ChatMessage[];
  suggestedPrompts: string[];
  suggestedPromptBatch: number;

  // Settings
  qualityMode: boolean;
  explainMode: boolean;

  // Loading
  isLoading: boolean;
  error: string | null;

  // Status tracking
  statusMessageId: string | null;

  // Actions
  setConversationId: (id: string | null) => void;
  addMessage: (message: ChatMessage) => void;
  setMessages: (messages: ChatMessage[]) => void;
  setSuggestedPrompts: (prompts: string[]) => void;
  regenerateSuggestedPrompts: (mapCenter?: { lat: number; lng: number } | null) => void;
  appendSuggestedPrompts: (mapCenter?: { lat: number; lng: number } | null) => void;
  setQualityMode: (enabled: boolean) => void;
  setExplainMode: (enabled: boolean) => void;
  setIsLoading: (isLoading: boolean) => void;
  setError: (error: string | null) => void;
  handleChatResponse: (response: ChatResponse) => void;
  clearConversation: () => void;
  updateStatusMessage: (messageId: string, status: StatusUpdate) => void;
  clearStatusMessage: (messageId: string) => void;
  setStatusMessageId: (id: string | null) => void;
}

export const useChatStore = create<ChatState>()(
  immer((set) => ({
    // Initial state
    conversationId: null,
    messages: [],
    suggestedPrompts: generateSuggestedPrompts(null, { count: 10, ridiculousnessLevel: 0 }),
    suggestedPromptBatch: 0,
    qualityMode: true,
    explainMode: true,
    isLoading: false,
    error: null,
    statusMessageId: null,

    // Actions
    setConversationId: (id) => set((state) => {
      state.conversationId = id;
    }),

    addMessage: (message) => set((state) => {
      state.messages.push(message);
    }),

    setMessages: (messages) => set((state) => {
      state.messages = messages;
    }),

    setSuggestedPrompts: (prompts) => set((state) => {
      state.suggestedPrompts = prompts;
    }),

    regenerateSuggestedPrompts: (mapCenter) => set((state) => {
      state.suggestedPromptBatch = 0;
      state.suggestedPrompts = generateSuggestedPrompts(mapCenter, { count: 10, ridiculousnessLevel: 0 });
    }),

    appendSuggestedPrompts: (mapCenter) => set((state) => {
      const nextBatch = state.suggestedPromptBatch + 1;
      const nextPrompts = generateSuggestedPrompts(mapCenter, {
        count: 10,
        ridiculousnessLevel: nextBatch,
        usedPrompts: state.suggestedPrompts,
      });
      state.suggestedPromptBatch = nextBatch;
      state.suggestedPrompts = [...state.suggestedPrompts, ...nextPrompts];
    }),

    setQualityMode: (enabled) => set((state) => {
      state.qualityMode = enabled;
    }),

    setExplainMode: (enabled) => set((state) => {
      state.explainMode = enabled;
    }),

    setIsLoading: (isLoading) => set((state) => {
      state.isLoading = isLoading;
    }),

    setError: (error) => set((state) => {
      state.error = error;
    }),

    handleChatResponse: (response) => set((state) => {
      state.conversationId = response.conversationId;
      state.messages.push(response.message);
      if (response.suggestedPrompts.length > 0) {
        state.suggestedPrompts = response.suggestedPrompts;
      }
    }),

    clearConversation: () => set((state) => {
      state.conversationId = null;
      state.messages = [];
      // Prompts will be regenerated by the component on mount
      state.error = null;
      state.statusMessageId = null;
    }),

    updateStatusMessage: (messageId, status) => set((state) => {
      // Find the status message - either by index or by checking if it's the active status message
      let messageIndex = -1;
      if (state.statusMessageId === messageId) {
        // Find the last status message if statusMessageId matches
        for (let i = state.messages.length - 1; i >= 0; i--) {
          if (state.messages[i].isStatus) {
            messageIndex = i;
            break;
          }
        }
      } else {
        // Try to find by index
        const idx = parseInt(messageId, 10);
        if (!isNaN(idx) && idx >= 0 && idx < state.messages.length) {
          messageIndex = idx;
        }
      }
      
      if (messageIndex !== -1 && state.messages[messageIndex].isStatus) {
        state.messages[messageIndex].statusUpdate = status;
        state.messages[messageIndex].content = status.message;
      }
    }),

    clearStatusMessage: (messageId) => set((state) => {
      // Find the status message to remove
      let messageIndex = -1;
      if (state.statusMessageId === messageId) {
        // Find the last status message if statusMessageId matches
        for (let i = state.messages.length - 1; i >= 0; i--) {
          if (state.messages[i].isStatus) {
            messageIndex = i;
            break;
          }
        }
      } else {
        // Try to find by index
        const idx = parseInt(messageId, 10);
        if (!isNaN(idx) && idx >= 0 && idx < state.messages.length) {
          messageIndex = idx;
        }
      }
      
      if (messageIndex !== -1 && state.messages[messageIndex].isStatus) {
        state.messages.splice(messageIndex, 1);
        if (state.statusMessageId === messageId) {
          state.statusMessageId = null;
        }
      }
    }),

    setStatusMessageId: (id) => set((state) => {
      state.statusMessageId = id;
    }),
  }))
);
